language: python
sudo: required
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7

env:
  matrix:
    - WTFORMS=1.0.4
    - WTFORMS=1.0.5
    - WTFORMS=2.0
    - WTFORMS=2.1
    - WTFORMS=2.2
    - WTFORMS=2.3
    - WTFORMS=3.0.0a1 SQLALCHEMY=1.4.0b1

install:
  - pip install WTForms==$WTFORMS
  - pip install -e ".[test]"
  - test -z $SQLALCHEMY || pip install SQLAlchemy==$SQLALCHEMY

script:
  - isort --recursive --diff wtforms_alchemy tests && isort --recursive --check-only wtforms_alchemy tests
  - flake8 wtforms_alchemy tests
  - py.test tests
